version: "3.8"

services:
  app:
    build: .
    container_name: azure_backend
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn AZURE.main:app --host 0.0.0.0 --port 8000 --reload
